# Assignment 2

Before working on this assignment please read these instructions fully. In the submission area, you will notice that you can click the link to **Preview the Grading** for each step of the assignment. This is the criteria that will be used for peer grading. Please familiarize yourself with the criteria before beginning the assignment.

An NOAA dataset has been stored in the file `data/C2A2_data/BinnedCsvs_d400/fb441e62df2d58994928907a91895ec62c2c42e6cd075c2700843b89.csv`. The data for this assignment comes from a subset of The National Centers for Environmental Information (NCEI) [Daily Global Historical Climatology Network](https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt) (GHCN-Daily). The GHCN-Daily is comprised of daily climate records from thousands of land surface stations across the globe.

Each row in the assignment datafile corresponds to a single observation.

The following variables are provided to you:

* **id** : station identification code
* **date** : date in YYYY-MM-DD format (e.g. 2012-01-24 = January 24, 2012)
* **element** : indicator of element type
    * TMAX : Maximum temperature (tenths of degrees C)
    * TMIN : Minimum temperature (tenths of degrees C)
* **value** : data value for element (tenths of degrees C)

For this assignment, you must:

1. Read the documentation and familiarize yourself with the dataset, then write some python code which returns a line graph of the record high and record low temperatures by day of the year over the period 2005-2014. The area between the record high and record low temperatures for each day should be shaded.
2. Overlay a scatter of the 2015 data for any points (highs and lows) for which the ten year record (2005-2014) record high or record low was broken in 2015.
3. Watch out for leap days (i.e. February 29th), it is reasonable to remove these points from the dataset for the purpose of this visualization.
4. Make the visual nice! Leverage principles from the first module in this course when developing your solution. Consider issues such as legends, labels, and chart junk.

The data you have been given is near **Ann Arbor, Michigan, United States**, and the stations the data comes from are shown on the map below.

In [ ]:
import matplotlib.pyplot as plt
import mplleaflet
import pandas as pd

def leaflet_plot_stations(binsize, hashid):

    df = pd.read_csv('data/C2A2_data/BinSize_d{}.csv'.format(binsize))

    station_locations_by_hash = df[df['hash'] == hashid]

    lons = station_locations_by_hash['LONGITUDE'].tolist()
    lats = station_locations_by_hash['LATITUDE'].tolist()

    plt.figure(figsize=(8,8))

    plt.scatter(lons, lats, c='r', alpha=0.7, s=200)

    return mplleaflet.display()


leaflet_plot_stations(400,'fb441e62df2d58994928907a91895ec62c2c42e6cd075c2700843b89')

In [1]:
%matplotlib
import pandas as pd
import numpy as np
import matplotlib as mp
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg

In [4]:
temp = pd.read_csv("temperature.csv")
temp

                 ID        Date Element  Data_Value
0       USW00094889  2014-11-12    TMAX          22
1       USC00208972  2009-04-29    TMIN          56
2       USC00200032  2008-05-26    TMAX         278
3       USC00205563  2005-11-11    TMAX         139
4       USC00200230  2014-02-27    TMAX        -106
5       USW00014833  2010-10-01    TMAX         194
6       USC00207308  2010-06-29    TMIN         144
7       USC00203712  2005-10-04    TMAX         289
8       USW00004848  2007-12-14    TMIN         -16
9       USC00200220  2011-04-21    TMAX          72
10      USC00205822  2013-01-16    TMAX          11
11      USC00205822  2008-05-29    TMIN          28
12      USC00203712  2008-10-17    TMIN          17
13      USC00205563  2006-05-14    TMAX         183
14      USC00200842  2006-05-14    TMAX         122
15      USC00205563  2014-12-07    TMAX          67
16      USC00205822  2008-09-07    TMAX         250
17      USC00205450  2006-04-22    TMIN          67
18      USC00203712  2008-02-22    TMAX         -44
19      USC00205563  2015-01-03    TMIN         -39
20      USC00201250  2011-03-28    TMIN         -78
21      USC00200230  2008-02-10    TMAX          -6
22      USC00207320  2008-02-03    TMIN         -39
23      USC00200228  2008-02-23    TMAX          11
24      USC00201250  2012-03-20    TMIN         100
25      USC00205822  2006-03-29    TMIN         -17
26      USC00202308  2006-05-11    TMAX         233
27      USW00014833  2012-03-31    TMAX          61
28      USW00014853  2010-07-25    TMAX         283
29      USC00205822  2014-12-09    TMIN          17
...             ...         ...     ...         ...
165055  USC00202308  2009-10-09    TMAX         111
165056  USC00200228  2015-02-23    TMAX         -11
165057  USC00208080  2009-11-24    TMAX         100
165058  USC00208972  2010-03-22    TMAX          94
165059  USC00207312  2015-06-23    TMIN         172
165060  USC00200230  2010-05-23    TMAX         283
165061  USW00004848  2012-12-26    TMIN         -32
165062  USC00205822  2014-02-06    TMAX         -11
165063  USC00200230  2010-05-23    TMIN         133
165064  USC00207312  2008-08-04    TMIN         172
165065  USC00200032  2006-03-01    TMAX          17
165066  USC00207312  2008-08-04    TMAX         306
165067  USC00207312  2005-12-31    TMAX          17
165068  USW00094889  2005-12-20    TMAX         -39
165069  USW00004848  2011-03-18    TMIN          44
165070  USC00208202  2011-11-26    TMIN          28
165071  USC00201250  2010-06-19    TMAX         294
165072  USC00208080  2015-11-14    TMIN         -17
165073  USC00205563  2005-05-13    TMAX         222
165074  USW00094889  2009-07-09    TMAX         261
165075  USC00205451  2014-10-03    TMIN         100
165076  USC00205050  2013-09-29    TMAX         261
165077  USC00205050  2014-07-14    TMIN         172
165078  USC00200032  2011-06-27    TMIN         144
165079  USC00202308  2005-03-02    TMIN         -67
165080  USC00205822  2015-06-09    TMAX         256
165081  USC00205822  2009-10-06    TMAX         167
165082  USC00205050  2014-07-14    TMAX         283
165083  USC00200230  2006-11-29    TMIN         117
165084  USC00207312  2006-09-04    TMIN         111

[165085 rows x 4 columns]

In [ ]:
tmax = []
tmin = []